import os
os.system("clear")
import time

print("ooi meu bem")
print(" ")
time.sleep(1.5)
print("sei que você não está nada bem mas")
print(" ")
time.sleep(1.5)
print("saiba q eu te amo ")
time.sleep(1.5)
print("___d88888888b_____d88888888b")
time.sleep(0.2)
print("__d88?____d88b___d88b____`88b")
time.sleep(0.2)
print("_d8?_________d888b_________`8b")
time.sleep(0.2)
print("_8b_________________________d8")
time.sleep(0.2)
print("_b8__________________d8888b___d8888b")
time.sleep(0.2)
print("__d8________________d8?__d8b_d8b__`8b")
time.sleep(0.2)
print("___8ba_____________d8?_____d8b_____`8b")
time.sleep(0.2)
print("____`8da___________8b_______________d8")
time.sleep(0.2)
print("______`Y8b__________d8_____________8b")
time.sleep(0.2)
print("________`8b__________8ba_________ad8")
time.sleep(0.2)
print("__________`88_____88__`8da_____ab8?")
time.sleep(0.2)
print("____________8b___d8_____`Y8___8Y?")
time.sleep(0.2)
print("_____________`b_d?________`8_8?")
time.sleep(0.2)
print("______________`8?__________`8?")
time.sleep(0.2)
print("_______________ ____________")
